### ISSUE TITLE
Fix table columns text overlap

### ISSUE THREAD

**Issue by matous-volf** [delta-cs/seminar-domjudge#126]
could we get rid of this?

![image](https://github.com/delta-cs/seminar-domjudge/assets/66163112/f5b05986-fb2a-4fdd-b992-26f3f5a956cf)

does the "subject" column have a fixed width?

_Originally posted by @matous-volf in https://github.com/delta-cs/seminar-domjudge/issues/122#issuecomment-2007071658_

**Comment by zapotocnylubos** [comment]
<img width="241" alt="Snímek obrazovky 2024-10-29 v 20 13 46" src="https://github.com/user-attachments/assets/d4fb5a66-e0fd-43be-93fb-28b79c0e4f0e">

it may be already fixed (by updating to 8.3.0)
