### ISSUE TITLE
The homepage cover is too compressed

### ISSUE THREAD

**Issue by matous-volf** [delta-cs/seminar-domjudge#139]
we've used WebP for the homepage cover image (#69) but maybe compressed it too much – it doesn't seem sharp:

![image](https://github.com/delta-cs/seminar-domjudge/assets/66163112/2a499f21-7258-4c33-bde3-04f9851a8929)

**Comment by zapotocnylubos** [comment]
[computer-programmer.zip](https://github.com/user-attachments/files/16795605/computer-programmer.zip)

**Comment by zapotocnylubos** [comment]
the original photo was not good enough,... I added the 4x ai upscaled version
