### ISSUE TITLE
Creating a problem with a text throws an error

### ISSUE THREAD

**Issue by matous-volf** [delta-cs/seminar-domjudge#152]
> An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '7' for key 'PRIMARY'

It seems the `INSERT INTO problem_statement_content` gets called twice.

**Comment by zapotocnylubos** [comment]
create an issue in domjudge upstream https://github.com/DOMjudge/domjudge/issues/2646

**Comment by zapotocnylubos** [comment]
fixed - cherry-picked change from upstream https://github.com/delta-cs/seminar-domjudge/commit/4ad6ace0868639c7cce8ba8ba3af6738943756b7
