### ISSUE TITLE
Create welcome notification for new users

### ISSUE THREAD

**Issue by zapotocnylubos** [delta-cs/seminar-domjudge#23]
New user does not receive welcome notification when registered, it would be nice to have welcome/tutorial message for each registered user

Some event after user is registered + config filed of type textarea with specified text for this default message would be ok solution

**Comment by zapotocnylubos** [comment]
Maybe better event handler would be when team (user) first access website using specific contest context.
Check, if user has 0 clarifications, if yes, create the clarification from default message.

We will add more and more contests for already created users, and for each contest, we need to create welcome message, because clarifications are scoped to the contest.

The welcome message can be static for all contests for now -> no need to configure per-contest specific default message

**Comment by matous-volf** [comment]
Resolved in #25.
