### ISSUE TITLE
More information for the user

### ISSUE THREAD

**Issue by matous-volf** [delta-cs/seminar-domjudge#32]
- on the homepage, instead of four recatngles, display two:
  1. current contest information and a link to the current contest problemset
  2. information about the seminar not being just a contest and a link to education problemset and materials
  - use #30

- currently just a button to view problems on GitHub, ideally explain why and what's there to find. maybe even add a nav item "educational materials".

- the archive is probably not necessary to have in the navigation, rather place it below the problemset.

- generally focus more on leading the user through the site

**Comment by zapotocnylubos** [comment]
1. Study odkaz v navbaru pro neprihlasene i prihlasene (vedle problemsetu)
2. odkaz na study v detailu problemsetu (odkaz na github pro ulohy a odkaz na github study materialy)\

**Comment by zapotocnylubos** [comment]
3. archiv nechat v public navbaru + ve vsech detailech problemsetu

**Comment by matous-volf** [comment]
resolved in #35 and #49
