### ISSUE TITLE
Obohatit popup pro zobrazovaní posledního data přihlášení

### ISSUE THREAD

**Issue by zapotocnylubos** [delta-cs/seminar-domjudge#48]
<img width="423" alt="Snímek obrazovky 2023-08-28 v 22 29 23" src="https://github.com/delta-cs/seminar-domjudge/assets/20317551/ecf5ab8f-ab39-4d54-bbc8-7a8c699bfe7b">

Při najetí na zelenou iknoku se zobrazuje čas posledního přihlášení, ale v DB to bude určitě datetime.

Hodilo by se do tohoto místa vložit i informaci o datu.

**Comment by matous-volf** [comment]
jo, tohle je na nekolika mistech v dj, treba u odevzdani reseni

**Comment by zapotocnylubos** [comment]
<img width="1465" alt="Snímek obrazovky 2023-08-30 v 14 14 51" src="https://github.com/delta-cs/seminar-domjudge/assets/20317551/99525f1a-02e4-4369-a6bd-d459db0da728">
Tady by se taky hodilo mit cele datum

**Comment by matous-volf** [comment]
@zapotocnylubos ono je to koukam v configu DJ :D
aplikuje se na vsech zminenych mistech

Display -> Time format

![image](https://github.com/delta-cs/seminar-domjudge/assets/66163112/01aef541-92c7-4c43-9971-93edc099fc6b)

**Comment by zapotocnylubos** [comment]
Luxus, nastavil jsem a uzaviram
