### ISSUE TITLE
Statice soubory a verzovani

### ISSUE THREAD

**Issue by zapotocnylubos** [delta-cs/seminar-domjudge#57]
Ted jsem udelal release 0.1.10, ve kterem bylo opraveni ccs.
Jelikoz ale nginx nechava klienta toto css zacahovat pod cestou ....style.css?v=8.2.1
tak se mi styly nenacetly nove (musel jsem v browser vycistit mezipamet)

Musime pridat k teto "base" domjudge verzi pridat i nejaky suffix, klidne i tak, aby to bylo ve vysledku style.css?v=8.2.1-0.0.10

**Comment by matous-volf** [comment]
@zapotocnylubos tohle by mohlo byt dobry: https://github.com/EmilePerron/git-version-strategy

jinak bys asi musel pri releasovani delat jeste zmenu v nejakem configu a prepsat tam tu nasi verzi jako treba "0.1.11"?

**Comment by zapotocnylubos** [comment]
upstream domjduge vzdy pro release tvori separatni vetev a nektere hodnoty v readme upravujou myslim..

pak v tom [packaging repozitari](https://github.com/delta-cs/seminar-domjudge-packaging) se to myslim nekde cetlo a prave nastavovalo jako hodnota pro ?v=....

**Comment by matous-volf** [comment]
`v=` se nastavuje ve [framework.yaml](https://github.com/delta-cs/seminar-domjudge/blob/01c55dbe701b82e99b4a94e758a83551e60e231a/webapp/config/packages/framework.yaml#L17). to bere `domjudge.version` ze static.yaml (gitignornute), coz se generuje ze [static.yaml.in](https://github.com/delta-cs/seminar-domjudge/blob/055f34e1574667a135694c708919460a70c7ca81/webapp/config/static.yaml.in#L4), ale to netusim, kde bere `@DOMJUDGE_VERSION@`.

ty bys to chtel nejak automatizovat, nebo staci, kdyz pri releasu nekde pripises tu nasi verzi?

**Comment by zapotocnylubos** [comment]
Mame buildici skript https://github.com/delta-cs/seminar-domjudge-packaging/blob/main/docker/build.sh
Kde by bylo mozne toto nejak automatizovat (mas promennou s aktualini release verzi)

**Comment by zapotocnylubos** [comment]
musi se to vyresit rychle, ted treba release s webp obrazkama vubec nezabral, dokuz jsem nedal v prohlizeni flusfh pameti

**Comment by zapotocnylubos** [comment]
(takze pro ostatni, co uz na webu byly to se ted bude zobrazovat rozbite)

**Comment by zapotocnylubos** [comment]
I kdy je divne, (myslim), ze jsem na te strance videl, ze v html stale bylo referencovane .png a ne .webp,..

**Comment by matous-volf** [comment]
> I kdy je divne, (myslim), ze jsem na te strance videl, ze v html stale bylo referencovane .png a ne .webp,..

a neni to ta /resolve routa? ta pak presmeruje na .webp

**Comment by zapotocnylubos** [comment]
me se hned po releasu zobrazila na HP velke sede pozadi

**Comment by matous-volf** [comment]
jo, HP je setnuta pres background-image v CSS, ktere se cachenulo. ja to png pozadi smazal. takze jak rikas, asi vyresit rychle. stacilo by treba pridat argument tomu build scriptu? prvni by byl "8.2.1" na ten dj tar.gz a druhy prave "0.1.13"?

**Comment by zapotocnylubos** [comment]
zde se taha version a defaultni promenna $PACKAGE_VERSION, ktera se pak nahrazuje ve vsech ruznych souborech za DOMJUDGE_VERSION

https://github.com/delta-cs/seminar-domjudge/blob/90bfc13e59418f94e49f8df93ff9e6c6c7bfde9f/configure.ac#L3

Zkusim do build skript pridat upravu do toho readme (pridat tam tu tag verzi tak, aby jsme to nemuseli vzdy manualne upravovat)

**Comment by zapotocnylubos** [comment]
a nebo to proste udelame manulne ted :D

**Comment by zapotocnylubos** [comment]
@matous-volf zatim jsem zkusil udelat specialni MR na pridani toho tagu manualne a zafungovalo to skvele

https://github.com/delta-cs/seminar-domjudge/pull/71/files

<img width="1087" alt="Snímek obrazovky 2023-09-25 v 9 45 04" src="https://github.com/delta-cs/seminar-domjudge/assets/20317551/85722412-0099-4c57-b873-8dee2376cf3a">

**Comment by zapotocnylubos** [comment]
budeme prozatim pridavat commit na prepsani verze v readme.md

**Comment by matous-volf** [comment]
mimochodem, je tohle normalni postup - parsovat verzi z readme? :D
