### ISSUE TITLE
Pri redirectu na cid= se "zapomenou" flash message

### ISSUE THREAD

**Issue by zapotocnylubos** [delta-cs/seminar-domjudge#62]
Zde se pridavalo presmerovani na specificky cid=

https://github.com/delta-cs/seminar-domjudge/pull/45

Ale v ramci jineho ticketu jsem narazil, ze pokud necham vygenerovat cestu naprikald na seznam ukolu, tak se vlastne jeste stane to presmerovani na cid= ale po tomto druhem redirectu uz ale nejsou k dispozici flash message

**Comment by matous-volf** [comment]
seznam ukolu - myslis problemset?

a jakou flash message treba myslis? na jake strance?

**Comment by zapotocnylubos** [comment]
generoval jsem flash message 
potom jsem vygeneroval redirect na problemset (bez specifickeho zadani cid query parametru)

uzivatele to poslalo na problem set,
le pak ho to jeste jednou poslalo na problemset + cid=

v tu dobu se asi pri renderovani problemset bez cid zapomneli flash messages?

**Comment by zapotocnylubos** [comment]
Ted se mi zase duplikovaly, resim
