### ISSUE TITLE
Pridat discord pozvanku na web

### ISSUE THREAD

**Issue by zapotocnylubos** [delta-cs/seminar-domjudge#79]
Pro efektivnejsi komunikace a oznameni (a retenci) muzeme jeste vyuzit ofiko discord pro pardubickeho hackera z minuleho roku

https://discord.gg/3w9Z6vXV

dal bych to na dve mista, nekdam do hlavicky webu jako ikonku discordu nebo nekam, kde si toho uzivatel vsimne 
a potom v dlouhe textove forme na kontaktni stranku pod kotakty asi

https://pardubicky-hacker.delta-skola.cz/public/authors

**Comment by zapotocnylubos** [comment]
url pozvanky nacitat z configu

**Comment by matous-volf** [comment]
nechceme to jeste hodit pod clarifications na team home?
![image](https://github.com/delta-cs/seminar-domjudge/assets/66163112/033e4fcd-93b3-43d5-bf68-0e42491b0c74)

**Comment by zapotocnylubos** [comment]
jj, takz muzeme, to je dobre misto, kde budou hledat pomoc

**Comment by matous-volf** [comment]
#87
