### ISSUE TITLE
Davat sample testcases na prvni misto

### ISSUE THREAD

**Issue by zapotocnylubos** [delta-cs/seminar-domjudge#96]
dat sample testcases na prvni misto v DJ. judging pote nejdrive kontroluje sample vstupy a vyreportuje uzivateli chybu a az pote konteoluje skryte vstupy.

myslim, ze u leku se ted stalo, jelikoz je sample nekde uprostred, ze judging byl oznacen jako nevalidni, ale sample testcase, ktery by se zobrazil uzivateli nebyl ani spusten

https://pardubicky-hacker.delta-skola.cz/jury/submissions/418

**Comment by zapotocnylubos** [comment]
@matous-volf koukam, ze jsi je prehazel, muzeme tedy issue uzavrit?

**Comment by matous-volf** [comment]
jj, u dalsich na to budu dbat

**Comment by zapotocnylubos** [comment]
@matous-volf koukni na to prosim jeste jednou na vsechny ulohy, u teto cvicne to neni
https://pardubicky-hacker.delta-skola.cz/jury/submissions/430
https://pardubicky-hacker.delta-skola.cz/jury/problems/6/testcases

**Comment by matous-volf** [comment]
ajo, diky - prosel jsem vsechny a snad uz dobry
